/**
 * 员工 intro（初始提示词/身份补充）与 AGENTS.md 瘦身模板的节点侧单元测试。
 *
 * dsh 用最小假对象（本链路只有 create 会注册工作区）。
 */

import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { EmployeeStore, INTRO_MAX_CHARS } from '../src/node/employees.ts'
import type { EmployeeManifest } from '../src/node/employees.ts'
import type { DshClient } from '../src/node/dsh-client.ts'

const fakeDsh = {
  workspaceCreate: async () => ({ workspaceId: 'w-test' }),
} as unknown as DshClient

/** 瘦身前的旧模板输出（内联留作体积基准，用来断言新模板明显变短）。 */
function renderLegacyAgentsMd(manifest: { name: string; role: string }): string {
  return `<!-- generated by DSEmployee -->
# ${manifest.name}

## 你是谁

你是 **${manifest.name}**，一个数字员工。

## 你负责什么

${manifest.role}

## 工作约定

- 你的工作区就是这个目录。你产出的文件默认放在这里。
- 需要长期记住的事实写进 \`memory/\` 或本文件，不要只留在对话里。
- 本文件（\`AGENTS.md\`）是你的岗位说明书与知识库入口，会被自动加载进每一次会话。
- 专属技能放在 \`.dsh/skills/\` 下，只对你生效。
- 不确定的事情先问，不要猜。任务越模糊，越要先确认再动手。

---

_本文件由 DSEmployee 生成。你若手工编辑并去掉开头那行标记，工具将不再自动覆盖它。_
`
}

async function withStore(run: (store: EmployeeStore) => Promise<void>): Promise<void> {
  const root = await mkdtemp(path.join(process.cwd(), '.tmp-intro-test-'))
  try {
    const store = new EmployeeStore(root, fakeDsh)
    await store.init()
    await run(store)
  } finally {
    await rm(root, { recursive: true, force: true })
  }
}

async function workspacePathOf(store: EmployeeStore, employeeId: string): Promise<string> {
  const { employees } = await store.discover()
  const found = employees.find((employee) => employee.id === employeeId)
  assert.ok(found, `employee ${employeeId} should exist`)
  return found.workspacePath
}

async function readManifest(store: EmployeeStore, employeeId: string): Promise<EmployeeManifest> {
  const workspacePath = await workspacePathOf(store, employeeId)
  const raw = await readFile(path.join(workspacePath, '.dsemployee', 'employee.json'), 'utf8')
  return JSON.parse(raw) as EmployeeManifest
}

async function readAgentsMd(store: EmployeeStore, employeeId: string): Promise<string> {
  const workspacePath = await workspacePathOf(store, employeeId)
  return await readFile(path.join(workspacePath, 'AGENTS.md'), 'utf8')
}

describe('员工 intro 与 AGENTS.md 瘦身模板', () => {
  it('create 带 intro：trim 后落盘，AGENTS.md 含「设定」行，返回值与 discover 透出', async () => {
    await withStore(async (store) => {
      const created = await store.create({
        name: '小默',
        role: '写周报',
        intro: '  口吻克制，先给结论。  ',
      })
      assert.equal(created.intro, '口吻克制，先给结论。')

      const manifest = await readManifest(store, created.id)
      assert.equal(manifest.intro, '口吻克制，先给结论。', '落盘的 intro 应是 trim 后的')

      const agentsMd = await readAgentsMd(store, created.id)
      assert.ok(agentsMd.includes('设定：口吻克制，先给结论。'))

      const { employees } = await store.discover()
      assert.equal(employees.find((e) => e.id === created.id)?.intro, '口吻克制，先给结论。')
    })
  })

  it('intro 缺省 / 空串 / 纯空白 = 不留存', async () => {
    await withStore(async (store) => {
      const without = await store.create({ name: '甲', role: 'r' })
      assert.equal((await readManifest(store, without.id)).intro, undefined)
      assert.ok(!(await readAgentsMd(store, without.id)).includes('设定：'))

      const blank = await store.create({ name: '乙', role: 'r', intro: '   ' })
      assert.equal((await readManifest(store, blank.id)).intro, undefined)
      assert.ok(!(await readAgentsMd(store, blank.id)).includes('设定：'))
    })
  })

  it('intro trim 后超长拒绝（create 与 update 都拒），恰好 500 字符可过', async () => {
    await withStore(async (store) => {
      const oversized = 'x'.repeat(INTRO_MAX_CHARS + 1)
      await assert.rejects(() => store.create({ name: '丙', role: 'r', intro: oversized }), /超长/)

      const ok = await store.create({ name: '丁', role: 'r', intro: 'x'.repeat(INTRO_MAX_CHARS) })
      assert.equal((await readManifest(store, ok.id)).intro, 'x'.repeat(INTRO_MAX_CHARS))

      // trim 后超长同样拒（前后空白不计入长度）
      const padded = `  ${'y'.repeat(INTRO_MAX_CHARS + 1)}  `
      await assert.rejects(() => store.update(ok.id, { intro: padded }), /超长/)
      // trim 后恰在上限则可过
      const trimmedFit = await store.update(ok.id, { intro: `  ${'z'.repeat(INTRO_MAX_CHARS)}  ` })
      assert.equal(trimmedFit.intro, 'z'.repeat(INTRO_MAX_CHARS))
    })
  })

  it('update 设置/修改 intro：manifest 与 AGENTS.md 同步重生，返回值带出', async () => {
    await withStore(async (store) => {
      const created = await store.create({ name: '小艾', role: '客服' })
      assert.ok(!(await readAgentsMd(store, created.id)).includes('设定：'))

      const updated = await store.update(created.id, { intro: '喜欢表格输出' })
      assert.equal(updated.intro, '喜欢表格输出')
      assert.equal((await readManifest(store, created.id)).intro, '喜欢表格输出')
      assert.ok((await readAgentsMd(store, created.id)).includes('设定：喜欢表格输出'))

      const revised = await store.update(created.id, { intro: '  改成简短的  ' })
      assert.equal(revised.intro, '改成简短的', 'update 也应 trim 后落盘')
      assert.ok((await readAgentsMd(store, created.id)).includes('设定：改成简短的'))
    })
  })

  it('update intro：null 与空串/纯空白都清除，AGENTS.md 同步去掉「设定」行', async () => {
    await withStore(async (store) => {
      const created = await store.create({ name: '阿澈', role: '运营', intro: '初版设定' })

      const clearedByNull = await store.update(created.id, { intro: null })
      assert.equal(clearedByNull.intro, undefined)
      assert.equal((await readManifest(store, created.id)).intro, undefined)
      assert.ok(!(await readAgentsMd(store, created.id)).includes('设定：'))

      await store.update(created.id, { intro: '再来一次' })
      const clearedByEmpty = await store.update(created.id, { intro: '' })
      assert.equal(clearedByEmpty.intro, undefined)
      assert.equal((await readManifest(store, created.id)).intro, undefined)

      await store.update(created.id, { intro: '第三次' })
      const clearedByBlank = await store.update(created.id, { intro: '   ' })
      assert.equal(clearedByBlank.intro, undefined)
      assert.equal((await readManifest(store, created.id)).intro, undefined)
      assert.ok(!(await readAgentsMd(store, created.id)).includes('设定：'))
    })
  })

  it('新模板明显变短：含 intro 时仍 < 旧模板字节的 60%', async () => {
    await withStore(async (store) => {
      const created = await store.create({
        name: '小测',
        role: '测试',
        intro: '先给结论',
      })
      const current = await readAgentsMd(store, created.id)
      const legacy = renderLegacyAgentsMd({ name: '小测', role: '测试' })
      const currentBytes = Buffer.byteLength(current, 'utf8')
      const legacyBytes = Buffer.byteLength(legacy, 'utf8')
      assert.ok(
        currentBytes < legacyBytes * 0.6,
        `新模板 ${currentBytes}B 应小于旧模板 ${legacyBytes}B 的 60%`,
      )
    })
  })

  it('手工去掉标记的 AGENTS.md 不被 update 覆盖', async () => {
    await withStore(async (store) => {
      const created = await store.create({ name: '小护', role: '看护', intro: '旧设定' })
      const workspacePath = await workspacePathOf(store, created.id)
      const mine = '# 我自己的岗位说明书\n\n这里的内容工具不许碰。\n'
      await writeFile(path.join(workspacePath, 'AGENTS.md'), mine, 'utf8')

      await store.update(created.id, { role: '新岗位', intro: '新设定' })
      assert.equal(await readAgentsMd(store, created.id), mine, '无标记文件必须原样保留')
      // manifest 照常更新，只是 AGENTS.md 不动
      assert.equal((await readManifest(store, created.id)).intro, '新设定')
    })
  })

  it('新标记行仍被识别为「可重写」；旧版标记（…DSEmployee -->）也继续生效', async () => {
    await withStore(async (store) => {
      // 新模板：update 改名后应重生且保留新标记行
      const fresh = await store.create({ name: '旧名', role: 'r' })
      assert.ok((await readAgentsMd(store, fresh.id)).includes('<!-- generated by DSEmployee'))
      await store.update(fresh.id, { name: '新名字' })
      const regenerated = await readAgentsMd(store, fresh.id)
      assert.ok(regenerated.includes('新名字'))
      assert.ok(regenerated.includes('<!-- generated by DSEmployee：手工编辑请删掉本行'))

      // 存量员工（旧模板 + 旧标记）：update 后应被重写为新模板
      const legacy = await store.create({ name: '老员工', role: '旧岗' })
      const legacyPath = await workspacePathOf(store, legacy.id)
      await writeFile(
        path.join(legacyPath, 'AGENTS.md'),
        renderLegacyAgentsMd({ name: '老员工', role: '旧岗' }),
        'utf8',
      )
      await store.update(legacy.id, { intro: '迁移过来的设定' })
      const migrated = await readAgentsMd(store, legacy.id)
      assert.ok(migrated.includes('设定：迁移过来的设定'))
      assert.ok(!migrated.includes('## 你是谁'), '旧模板应被替换为瘦身模板')
    })
  })
})
