/**
 * 给某个员工开通"调用其他员工"的能力 —— 把入口装进它的工作区。
 *
 * 为什么入口要装在**工作区里**、而不是做成一个全局命令：
 *   · 每个员工的凭据是**绑定身份**的（令牌只能以它自己名义发起调用），所以身份
 *     文件天然属于这个工作区（`<工作区>/.dse/`），彼此隔离；
 *   · 包装脚本里把 hub 地址与身份路径写死，agent 没法"顺手"指向别的凭据 ——
 *     这也是把"能不能冒名"从**提示词约束**变成**文件系统约束**。
 *
 * 三样东西：
 *   1. `<工作区>/.dse/config.json` —— hub 地址、员工 id、脚本要用的 dse 可执行文件
 *   2. `<工作区>/tools/employee-call` —— 薄包装：`employee-call <method> '<json>'`
 *   3. `<工作区>/.dsh/skills/employee-call/SKILL.md` —— 告诉 agent 有这个能力、
 *      以及**异步语义**（发起即返回，结果要另外去取，绝不能死等或编造）
 *
 * 凭据本身不在这一步产生：先跑一次脚本 → 它发起配对请求 → 人在 Hub 机器上
 * **显式批准并绑定到这个员工**（`dse pair approve <id> --employee <名字> …`）。
 * 信任锚点必须是人，这里只负责把入口摆好。
 */

import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises'
import { pathExists } from '../util/fsx.ts'
import path from 'node:path'

/** 员工凭据默认申请的 scope：读目录（知道有哪些同事）+ 发起调用。 */
export const CAPABILITY_SCOPES = ['employee.read', 'employee.invoke'] as const

export interface CapabilityOptions {
  /** 员工工作区（绝对路径） */
  workspace: string
  /** Hub 的 WebSocket 地址，例如 ws://127.0.0.1:19791/ws 或 wss://…/ws */
  hubUrl: string
  /** 写进包装脚本的 dse 可执行入口（绝对路径，通常是 <repo>/bin/dse.mjs） */
  dseBin: string
  /** 覆盖技能目录（默认 `<工作区>/.dsh/skills`） */
  skillsDir?: string
  /** 覆盖身份文件名（默认 `.dse/employee-identity.json`） */
  identityFile?: string
  /** 覆盖平台判断（默认 process.platform；测试用） */
  platform?: NodeJS.Platform
}

export interface CapabilityResult {
  employeeId: string
  employeeName: string
  /** 这次写/改了哪些文件（相对工作区） */
  files: string[]
  /** 人接下来要在 Hub 机器上执行的命令（含"先跑一次拿 requestId"的前置步骤） */
  nextSteps: string[]
}

/** 工作区里的员工档案（节点发现时写的）。 */
interface EmployeeFile {
  id?: unknown
  name?: unknown
}

const GITIGNORE_LINE = '.dse/'

/**
 * 入口的实际逻辑，放在一个 Node 脚本里（`tools/employee-call.mjs`）。
 *
 * 为什么不是直接写成 shell/批处理：**Windows 那套踩过三个坑**（都由员工实测报回来）——
 *   ① 工作区路径含中文（`数字员工`），写进 `.cmd` 会被 cmd 按 CP936 解码成乱码
 *      （`digital-employees` 变成 `tal-employees`）；
 *   ② 只写 LF 的 `.cmd` 在 cmd 里读错位，报一堆 `'oint.' is not recognized`；
 *   ③ 直接执行 `.mjs`（没有 `node` 前缀）**不报错，而是挂死**（等文件关联），
 *      放进自动化就是静默卡住。
 * 把逻辑交给 Node 之后，中文路径、引号、行尾这些问题一次性消失：shell 包装只剩一行，
 * 而且必须是**纯 ASCII**（路径全靠运行时展开，不落字面量）。
 *
 * 这个脚本读 `.dse/config.json`（UTF-8，Node 解码 ✓）拿 hub 地址与 dse 入口，
 * 身份与 home 固定为同目录下的 `.dse/` —— 于是它**只能以这个工作区绑定的身份**发起调用。
 */
function entryScript(): string {
  /* 注意：整段保持 ASCII，注释也用英文 —— 这个文件要能在 CP936 的 cmd 环境里被原样搬运。 */
  return [
    '#!/usr/bin/env node',
    '/*',
    ' * Employee-to-employee entry point (generated by `dse employee-capability`).',
    ' *',
    ' * Do not edit: regenerate instead. Everything it needs lives next to it:',
    ' *   .dse/config.json              hub URL + path to the dse CLI',
    ' *   .dse/employee-identity.json   this workspace\'s device key',
    ' *   .dse/token.json               claimed on first successful connect',
    ' *',
    ' * Usage (any platform, any shell):',
    ' *   tools/employee-call.mjs employee.list --params-file params.json',
    ' *   tools/employee-call.mjs employee.invoke --params-file invoke.json',
    ' *',
    ' * Prefer --params-file over inline JSON: cmd and PowerShell eat the quotes',
    ' * around inline JSON. Writing the arguments to a file always works.',
    ' */',
    "import { execFileSync } from 'node:child_process'",
    "import { existsSync, readFileSync } from 'node:fs'",
    "import path from 'node:path'",
    "import { fileURLToPath } from 'node:url'",
    '',
    'const here = path.dirname(fileURLToPath(import.meta.url))',
    "const workspace = path.resolve(here, '..')",
    "const dseDir = path.join(workspace, '.dse')",
    "const configPath = path.join(dseDir, 'config.json')",
    '',
    'let config',
    'try {',
    "  config = JSON.parse(readFileSync(configPath, 'utf8'))",
    '} catch (error) {',
    "  console.error('[employee-call] cannot read ' + configPath + ': ' + (error && error.message ? error.message : String(error)))",
    '  process.exit(2)',
    '}',
    '',
    "const dseBin = String(config.dseBin || '')",
    "const hubUrl = String(config.hubUrl || '')",
    "if (dseBin === '' || hubUrl === '') {",
    "  console.error('[employee-call] ' + configPath + ' is missing dseBin or hubUrl')",
    '  process.exit(2)',
    '}',
    "const identity = path.join(dseDir, 'employee-identity.json')",
    "if (!existsSync(identity)) {",
    "  console.error('[employee-call] no device identity at ' + identity + ' -- run the provisioning step again')",
    '  process.exit(2)',
    '}',
    '',
    '/* Pass everything through; the CLI appends nothing of its own. */',
    "const args = [dseBin, 'rpc', ...process.argv.slice(2), '--hub', hubUrl, '--identity', identity, '--home', dseDir]",
    'try {',
    "  execFileSync(process.execPath, args, { stdio: 'inherit' })",
    '} catch (error) {',
    '  process.exit(typeof error.status === "number" ? error.status : 1)',
    '}',
    '',
  ].join('\n')
}

/** POSIX 包装：一行，纯 ASCII（路径靠运行时展开）。 */
function wrapperScriptPosix(): string {
  return [
    '#!/bin/sh',
    '# Employee-to-employee entry point (generated). Real logic: employee-call.mjs',
    'exec node "$(dirname "$0")/employee-call.mjs" "$@"',
    '',
  ].join('\n')
}

/**
 * Windows 包装：**一行**，纯 ASCII。
 *
 * 单行是刻意的：员工实测报回来"只写 LF 的 .cmd 会被 cmd 读错位"（报一堆
 * `'oint.' is not recognized`）。单行文件没有行尾可言，从根上绕开。
 * `%~dp0` 是脚本自身所在目录（运行时展开）⇒ 中文工作区路径不落进文件里。
 */
function wrapperScriptWindows(): string {
  return '@echo off & node "%~dp0employee-call.mjs" %*\r\n'
}

function skillText(options: { employeeName: string }): string {
  return `---
name: employee-call
description: 调用其他数字员工干活（发起即返回，结果要另外去取）。当任务需要别的员工的专业能力、或需要它去操作它自己那台机器/那套账号时使用。
---

# 调用其他数字员工

入口（在工作区根目录下执行）：**这个入口只代表你**（${options.employeeName}）—— 不能以别人的名义发起。

- Windows（PowerShell / cmd）：\`tools\\employee-call.cmd <方法> --params-file params.json\`
- macOS / Linux：\`tools/employee-call <方法> --params-file params.json\`

参数一律**写进文件再传路径**（cmd 与 PowerShell 会吃掉内联 JSON 的引号，写文件永远可靠）。
两个包装都只是壳，真正的逻辑在同目录的 employee-call.mjs（它读 .dse/config.json）。

## 先看有哪些同事

\`\`\`bash
tools/employee-call employee.list '{}'
\`\`\`

从返回里取 \`id\`（\`emp_…\`）与 \`name\`；\`nodeOnline: false\` 表示它那台机器现在不在线。

## 派活

\`\`\`bash
tools/employee-call employee.invoke '{"toEmployeeId":"emp_xxx","task":"把这份 CSV 按月份汇总，只回结论"}'
\`\`\`

返回形如：

\`\`\`json
{"invokeId":"inv_…","status":"queued","dispatch":"started","note":"执行已在后台开始…"}
\`\`\`

**这是"已经派出去"，不是"已经做完"。** 一次调用可能跑几分钟（上限 15 分钟）。

## 取结果

\`\`\`bash
tools/employee-call employee.invoke.list '{}'
\`\`\`

找到你那条 \`invokeId\`：

| status | 含义 | 你该做什么 |
|---|---|---|
| \`queued\` / \`running\` | 还在排队或正在做 | 先干别的，稍后再查；**不要在一个回合里反复轮询死等** |
| \`pending-approval\` | 等授权终端批准 | 告诉用户"已派发，等批准"，不要当成失败 |
| \`completed\` | 完成，读 \`resultText\` | 把结果用于你的任务 |
| \`failed\` | 失败，读 \`error\` | 如实汇报失败原因；必要时换个说法重派 |

## 硬性约束

- **不许编造**：没拿到 \`resultText\` 就只能说"还没回来"或"派发失败"。绝不要凭想象写"某某说……"。
- **目标机器离线不算失败**：状态会停在 \`queued\`，等它上线后自动送出。
- **默认需要授权**：首次调用某位同事可能落到用户的审批队列（\`pending-approval\`）。这是正常的，不是错误。
- 只能派活、不能替对方做决定；对方的输出要如实转述，别加工成事实。
`
}

/**
 * 把一个员工工作区配置成"可以调用其他员工"。可重复执行（幂等）。
 */
export async function provisionEmployeeCapability(
  options: CapabilityOptions,
): Promise<CapabilityResult> {
  const workspace = path.resolve(options.workspace)
  const employeeFile = path.join(workspace, '.dsemployee', 'employee.json')
  let raw: EmployeeFile
  try {
    raw = JSON.parse(await readFile(employeeFile, 'utf8')) as EmployeeFile
  } catch (error) {
    throw new Error(
      `读不到员工档案 ${employeeFile} —— 这个目录不是数字员工工作区？` +
        `（原始错误：${error instanceof Error ? error.message : String(error)}）`,
    )
  }
  const employeeId = typeof raw.id === 'string' ? raw.id : ''
  const employeeName = typeof raw.name === 'string' ? raw.name : employeeId
  if (employeeId === '') {
    throw new Error(`${employeeFile} 里没有 id —— 工作区未完成初始化，先让节点重新发现一次`)
  }

  const identityRel = options.identityFile ?? path.join('.dse', 'employee-identity.json')
  const files: string[] = []

  // 1) .dse/config.json（身份与令牌由 dse rpc 首次连接时落在同一目录）
  const dseDir = path.join(workspace, '.dse')
  await mkdir(dseDir, { recursive: true })
  const configPath = path.join(dseDir, 'config.json')
  await writeFile(
    configPath,
    JSON.stringify(
      {
        employeeId,
        employeeName,
        hubUrl: options.hubUrl,
        dseBin: options.dseBin,
        scopes: [...CAPABILITY_SCOPES],
        createdAtMs: Date.now(),
        note: '由 dse employee-capability 生成；身份文件 employee-identity.json 与 token.json 也在这个目录里，别提交进 git',
      },
      null,
      2,
    ) + '\n',
    'utf8',
  )
  files.push(path.relative(workspace, configPath))

  // 2) 入口：逻辑在 .mjs，两个平台各一个一行的薄包装
  const toolsDir = path.join(workspace, 'tools')
  await mkdir(toolsDir, { recursive: true })

  const entryPath = path.join(toolsDir, 'employee-call.mjs')
  await writeFile(entryPath, entryScript(), 'utf8')
  files.push(path.relative(workspace, entryPath))

  const posixPath = path.join(toolsDir, 'employee-call')
  await writeFile(posixPath, wrapperScriptPosix(), 'utf8')
  await chmod(posixPath, 0o755)
  files.push(path.relative(workspace, posixPath))

  /* Windows 上一并写 .cmd：两种平台都摆好，员工在哪个 shell 里都能用。
     只写 bash 版曾让"这台机器上的员工没有这个能力"变成一个纯环境问题。 */
  if ((options.platform ?? process.platform) === 'win32') {
    const cmdPath = path.join(toolsDir, 'employee-call.cmd')
    await writeFile(cmdPath, wrapperScriptWindows(), 'utf8')
    files.push(path.relative(workspace, cmdPath))
  }

  // 3) .gitignore：身份与令牌绝不能进 git（工作区自己是 git 仓库）
  const gitignorePath = path.join(workspace, '.gitignore')
  const existing = await readFile(gitignorePath, 'utf8').catch(() => '')
  if (!existing.split('\n').some((line) => line.trim() === GITIGNORE_LINE)) {
    const next = existing === '' || existing.endsWith('\n') ? existing + GITIGNORE_LINE + '\n' : existing + '\n' + GITIGNORE_LINE + '\n'
    await writeFile(gitignorePath, next, 'utf8')
    files.push('.gitignore')
  }

  // 4) 技能：告诉 agent 有这条路，以及异步语义
  const skillsDir = options.skillsDir ?? path.join(workspace, '.dsh', 'skills')
  const skillDir = path.join(skillsDir, 'employee-call')
  await mkdir(skillDir, { recursive: true })
  const skillPath = path.join(skillDir, 'SKILL.md')
  await writeFile(skillPath, skillText({ employeeName }), 'utf8')
  files.push(path.relative(workspace, skillPath))

  return {
    employeeId,
    employeeName,
    files,
    nextSteps: [
      `在员工工作区跑一次（它只会在 Hub 上留一条**待批准**的配对请求）：`,
      `  cd "${workspace}" && tools/employee-call employee.list '{}'`,
      `在 Hub 机器上批准并把设备绑定到这个员工（信任锚点在这一步，必须由人做）：`,
      `  dse pair approve <上面打印的 requestId> --employee ${employeeName} --scopes ${CAPABILITY_SCOPES.join(',')}`,
      `批准后回到工作区再跑一次同样的命令 —— 这次会自动领取令牌并真正列出同事。`,
    ],
  }
}

/* ────────────────────────────── 秘书：每日汇总 ────────────────────────────── */

function digestSkillText(options: { employeeName: string; atTime: string }): string {
  return `---
name: daily-digest
description: 汇总其他数字员工最近的活儿并向用户汇报/提醒。当用户问"他们最近干了什么"、或到了每日汇报时间时使用。
---

# 每日汇总与提醒

你是 **${options.employeeName}**。你的活是：把其他同事最近的动向收上来，给用户一份**能看懂的短汇报**，
并把需要用户拍板或注意的事提醒出来。默认每天 ${options.atTime} 做一次（定时任务驱动）。

## 一、先拿事实（不要凭印象写）

\`\`\`bash
tools/employee-call employee.activity '{"windowHours":24}'
\`\`\`

返回的是**元数据**：每位员工的定时任务执行记录（谁/何时/成或败）、互调记录（谁派给谁什么、
结果如何）、审批（谁在等谁批）、以及会话活跃度（多少个、最近啥时候动过）。

- 想看某位同事**具体说了什么**，再单独读它的会话历史（\`session.history\`）—— 这是"下钻"，
  只在你确实需要引用原话时做，并在汇报里说明"这句话来自某会话"。不要例行把每个人的对话都拉一遍。
- 元数据里出现 \`notes\` 时**必须在汇报里带上**：那通常意味着某台机器离线、数据不全。

## 二、写汇报（给用户看的那一份）

结构固定成四段，短句，别写小作文：

1. **发生了什么**（3–6 条，按重要性排；每条一行：谁、做了什么、结果）
2. **要注意的**（失败/排队没送出去/连续失败被停用的任务/等了很久的审批）
3. **需要你决定的**（卡在审批上的、目标不明确的）
4. **数据说明**（窗口多长、哪台机器离线导致哪部分没算进来）

## 三、把汇报交出去

默认：**把汇报写在你自己的回复里**（用户打开控制台就能看到），写完就算交付。

如果用户给了投递地址（例如某个群机器人的 Webhook URL），就按那个地址发；发送失败**不要静默**：
把失败原因写进正文里，并保留汇报文本（下次重试）。

**不要假设本机装了任何聊天工具** —— 这台机器上通常没有钉钉/微信的登录态（真实教训：技能初版
写着"用钉钉发"，而该机从未登录过钉钉，那一整步等于不存在）。需要"发给某人"而本机没有渠道时，
**请有渠道的同事代发**：用 employee.invoke 说清发什么、发给谁，并把对方回复如实转述。

## 四、硬性约束

- **不许编造**：元数据里没有的事不要写。"某某说……"必须来自你实际读到的内容。
- **不许把"没有数据"说成"没有活动"**：notes 里写了什么就照实说什么。
- 汇报里**不要**包含 token、密钥、完整路径等敏感信息。
- 一天一次就够：没有新动向时，一句"今天没有新的动向"也是合格的汇报。
`
}

export interface DigestOptions {
  /** 员工工作区（绝对路径） */
  workspace: string
  /** 覆盖技能目录（默认 `<工作区>/.dsh/skills`） */
  skillsDir?: string
  /** 汇报时间（HH:MM，默认 09:00）—— 只写进技能说明与给出的命令里，不在本步创建任务 */
  atTime?: string
}

export interface DigestResult {
  employeeId: string
  employeeName: string
  files: string[]
  /** 建议的定时任务创建命令（由**人**执行：它要 employee.manage，不该发给员工） */
  scheduleCommand: string
}

/**
 * 给一个已经装好互调入口的员工补上"每日汇总"技能。
 *
 * 为什么要求先装 `tools/employee-call`：秘书取数走的就是那条通道（同一份绑定身份）。
 * 两套凭据只会让人搞不清"到底以谁的身份在调"，所以这里只补技能，不另发凭据。
 */
export async function provisionDailyDigest(options: DigestOptions): Promise<DigestResult> {
  const workspace = path.resolve(options.workspace)
  const employeeFile = path.join(workspace, '.dsemployee', 'employee.json')
  let raw: EmployeeFile
  try {
    raw = JSON.parse(await readFile(employeeFile, 'utf8')) as EmployeeFile
  } catch (error) {
    throw new Error(
      `读不到员工档案 ${employeeFile} —— 这个目录不是数字员工工作区？` +
        `（原始错误：${error instanceof Error ? error.message : String(error)}）`,
    )
  }
  const employeeId = typeof raw.id === 'string' ? raw.id : ''
  const employeeName = typeof raw.name === 'string' ? raw.name : employeeId
  if (employeeId === '') throw new Error(`${employeeFile} 里没有 id`)

  const wrapper = path.join(workspace, 'tools', 'employee-call')
  if (!(await pathExists(wrapper))) {
    throw new Error(
      `这个工作区还没有互调入口（缺 tools/employee-call）。先跑：` +
        `dse employee-capability --workspace "${workspace}" --hub <ws-url>`,
    )
  }

  const atTime = options.atTime ?? '09:00'
  const skillsDir = options.skillsDir ?? path.join(workspace, '.dsh', 'skills')
  const skillDir = path.join(skillsDir, 'daily-digest')
  await mkdir(skillDir, { recursive: true })
  const skillPath = path.join(skillDir, 'SKILL.md')
  await writeFile(skillPath, digestSkillText({ employeeName, atTime }), 'utf8')

  const [hours, minutes] = atTime.split(':')
  const scheduleCommand =
    `dse rpc job.upsert '{"name":"每日汇总","employeeId":"${employeeId}",` +
    `"prompt":"按 daily-digest 技能做今天的汇总：先 employee.activity 取事实，再写四段汇报并推送给用户。",` +
    `"intervalMinutes":1440}' --hub <ws-url>   ` +
    `# 建完在控制台「定时」页把它改成每天 ${hours}:${minutes}（用「编辑」调整间隔/时间）`

  return {
    employeeId,
    employeeName,
    files: [path.relative(workspace, skillPath)],
    scheduleCommand,
  }
}

/* ────────────────────────────── 总控：拆活派活 ────────────────────────────── */

function orchestrateSkillText(options: { employeeName: string }): string {
  return `---
name: orchestrate
description: 把一件活拆开、派给其他数字员工去做，再把结果收回来汇总。当任务需要别的同事的专业能力、或要同时联调多个系统时使用。
---

# 拆活、派活、收结果

你是 **${options.employeeName}**，在这类任务里充当"总控"：把一件大事拆成几件小事，
派给合适的同事，最后把结果收拢成一份给用户的答复。

入口：\`tools/employee-call <方法> '<JSON>'\`（这个入口只代表你自己）。

## 一、先看有谁、它们在不在

\`\`\`bash
tools/employee-call employee.list '{}'
\`\`\`

记下 \`id\`、\`name\`、\`position\`（工种）与 \`nodeOnline\`。**别派给不在线的同事**：
离线时指令会进队列（不会丢），但你现在拿不到结果。

## 二、派活（关键：发起即返回，不是"做完"）

\`\`\`bash
tools/employee-call employee.invoke '{"toEmployeeId":"emp_xxx","task":"具体、可验收的一句话"}'
\`\`\`

返回 \`{"invokeId":"inv_…","status":"queued"}\` 意思是**已经派出去**了。
一次调用可能跑几分钟（上限 15 分钟），**不要在一个回合里反复轮询死等** ——
先把你手上的活干完，需要结果时再查（见下）。

派活的写法：
- 一句话说清"要什么产出"（"把这份 CSV 按月份汇总，只回结论"），不要只说"看一下"。
- 需要多个同事协作时，**各派各的**（互不依赖的活并行派出去），不要串成一长串。

## 三、收结果

\`\`\`bash
tools/employee-call employee.invoke.list '{}'
\`\`\`

按 \`invokeId\` 找自己那几条：

| status | 含义 | 你该做什么 |
|---|---|---|
| \`queued\` / \`running\` | 还在排队/在做 | 先干别的；本轮就把"已派发，等结果"告诉用户 |
| \`pending-approval\` | 等用户批准 | 明说卡在审批，不要当失败 |
| \`completed\` | 读 \`resultText\` | 用它的结论继续你的活 |
| \`failed\` | 读 \`error\` | 如实说失败原因；判断要不要换个说法重派 |

## 四、汇总给用户

- 只写**实际拿到的**结果：谁做了什么、结论是什么。
- 还在跑的：单独列一节"进行中"，写明约多久后能看结果。
- 失败了：写清失败原因与你下一步打算（重派 / 找用户确认 / 放弃）。
- **不许编造**：没拿到 \`resultText\` 就只能说"还没回来"。

## 五、边界

- 你只能派活，不能替对方做决定；对方的输出要如实转述，别加工成事实。
- 对方返回的结论若与你的预期冲突，先如实报差异，不要替它"修正"。
- 卡住超过两轮（重派也不行）就停下问用户，不要空转。
`
}

export interface OrchestrateResult {
  employeeId: string
  employeeName: string
  files: string[]
}

/** 给已经装好互调入口的员工补上"总控"技能（拆活/派活/收结果的纪律）。 */
export async function provisionOrchestrateSkill(options: {
  workspace: string
  skillsDir?: string
}): Promise<OrchestrateResult> {
  const workspace = path.resolve(options.workspace)
  const employeeFile = path.join(workspace, '.dsemployee', 'employee.json')
  let raw: EmployeeFile
  try {
    raw = JSON.parse(await readFile(employeeFile, 'utf8')) as EmployeeFile
  } catch (error) {
    throw new Error(
      `读不到员工档案 ${employeeFile} —— 这个目录不是数字员工工作区？` +
        `（原始错误：${error instanceof Error ? error.message : String(error)}）`,
    )
  }
  const employeeId = typeof raw.id === 'string' ? raw.id : ''
  const employeeName = typeof raw.name === 'string' ? raw.name : employeeId
  if (employeeId === '') throw new Error(`${employeeFile} 里没有 id`)

  const wrapper = path.join(workspace, 'tools', 'employee-call')
  if (!(await pathExists(wrapper))) {
    throw new Error(
      `这个工作区还没有互调入口（缺 tools/employee-call）。先跑：` +
        `dse employee-capability --workspace "${workspace}" --hub <ws-url>`,
    )
  }

  const skillsDir = options.skillsDir ?? path.join(workspace, '.dsh', 'skills')
  const skillDir = path.join(skillsDir, 'orchestrate')
  await mkdir(skillDir, { recursive: true })
  const skillPath = path.join(skillDir, 'SKILL.md')
  await writeFile(skillPath, orchestrateSkillText({ employeeName }), 'utf8')

  return { employeeId, employeeName, files: [path.relative(workspace, skillPath)] }
}
